services:
  backend:
    image: amserdion/behealthybe:main
    ports:
      - "8080:8080"
    environment:
      - DSN=postgres://postgres:postgrespw@host.docker.internal:5432/postgres?sslmode=disable
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespw
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres